language: minimal

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q
  - sudo apt-get update
  - sudo apt-get -y install jq

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash  -s -x -- -g "1.13.4"

notifications:
  email:
    on_success: never
    on_failure: always